Add button component
eduardconstantin/azure-fundamentals pull request #25
Opened 2023-05-04 12:33 UTC by milafreckled

Fixes #0000 

- [ ] I have read and agree to the [Code of Conduct](https://github.com/eduardconstantin/azure-fundamentals/blob/main/CODE_OF_CONDUCT.md), and have followed the [Contributing guidelines](https://github.com/eduardconstantin/azure-fundamentals/blob/main/CONTRIBUTING.md).

## Pull Request Type

- [ ] Bug fix (please link related issues if applicable)
- [ ] New feature
- [ ] Question update
- [ ] Other

## Summary

2023-05-04 15:50 UTC, eduardconstantin requested changes
Thank you the the contribution, there are a few things you need to change, also please replace the old buttons on the page.

2023-05-04 15:50 UTC, eduardconstantin commented on components/Button.tsx
> +            class:  ['text-white', 'rounded-lg', 'text-base/6', 'focus:outline-none', 'focus:ring-1'],
you can move the default classes in the className prop

2023-05-04 15:50 UTC, eduardconstantin commented on components/Button.tsx
> +}) => <button className={button({ intent, size, className})} { ...props} />
it should look like this
```suggestion
={`${button({ intent, size })} text-white rounded-lg focus:outline-none focus:ring-1 border mb-2 sm:mb-0`}
```

2023-05-04 15:50 UTC, eduardconstantin commented on components/Button.tsx
> +            medium: ['font-medium', 'text-xs', 'py-2.5', 'mb-2', 'px-5'],
```suggestion
            medium: ['font-medium', 'py-2.5', 'px-5', 'sm:text-sm', 'text-xs'],
```

2023-05-04 15:50 UTC, eduardconstantin commented on components/Button.tsx
> +            primary: ['border', 'bg-blue-600/50', 'border-blue-600', 'hover:bg-emerald-600/60',
```suggestion
           primary: ["bg-blue-600/50", "border-blue-600", "hover:bg-blue-600/60", "focus:ring-blue-800", "border-blue-600"],
```

2023-05-04 15:50 UTC, eduardconstantin commented on components/Button.tsx
> +            secondary: ['bg-emerald-600/50', 'border-emerald-600', 'hover:bg-blue-600/60',
```suggestion
            secondary: [
        "bg-emerald-600/50",
        "border-emerald-600",
        "hover:bg-emerald-600/60",
        "focus:ring-green-800",
        "border-emerald-600",
        "sm:mr-2",
      ],
```

2023-05-05 17:31 UTC, eduardconstantin commented
@milafreckled could you resolve the other change requests?

2023-05-05 20:21 UTC, milafreckled commented
@eduardconstantin i've just resolved, could you check if everything is ok?

2023-05-06 07:06 UTC, eduardconstantin requested changes

2023-05-06 07:06 UTC, eduardconstantin commented on components/Button.tsx
> +            class:  ['text-white', 'rounded-lg', 'text-base/6', 'focus:outline-none', 'focus:ring-1'],
this can be removed
```suggestion
          
```

2023-05-07 09:12 UTC, eduardconstantin approved these changes

2023-05-07 09:15 UTC, merged