Implement exam quiz
eduardconstantin/azure-fundamentals pull request #65
Opened 2023-10-02 17:24 UTC by masterHAWK99

Fixes #60  

- [ ] I have read and agree to the [Code of Conduct](https://github.com/eduardconstantin/azure-fundamentals/blob/main/CODE_OF_CONDUCT.md), and have followed the [Contributing guidelines](https://github.com/eduardconstantin/azure-fundamentals/blob/main/CONTRIBUTING.md).

## Pull Request Type

- [x] New feature

## Summary

2023-10-03 17:06 UTC, eduardconstantin requested changes
This looks really good, there are a few changes to be made

2023-10-03 17:13 UTC, eduardconstantin requested changes

2023-10-03 17:13 UTC, eduardconstantin commented on components/ExamResult.tsx
> +      <p className="text-white text-lg">{render}</p>
```suggestion
      <p className="text-white text-lg mb-12">{render}</p>
```

2023-10-05 13:54 UTC, masterHAWK99 commented on pages/exam/index.tsx
> +            {currentQuestionIndex}/{numberOfQuestions}
In practice mode, the index starts from 0. Would you like me to apply this there as well?

2023-10-05 16:18 UTC, eduardconstantin requested changes

2023-10-05 16:18 UTC, eduardconstantin commented on pages/exam/index.tsx
> +  const numberOfQuestions = 30;
Don't hardcode the number of questions, use the length from the query

2023-10-05 17:46 UTC, masterHAWK99 commented on pages/exam/index.tsx
> +            {currentQuestionIndex}/{numberOfQuestions}
Sure, but for both?

2023-10-05 17:53 UTC, eduardconstantin commented on pages/exam/index.tsx
> +            {currentQuestionIndex}/{numberOfQuestions}
Yes

2023-10-05 18:16 UTC, eduardconstantin approved these changes
Thank you!

2023-10-05 18:16 UTC, merged