mass
eduardconstantin/azure-fundamentals pull request #74
Opened 2023-10-09 20:57 UTC by raviikushh

- Made Changes in UI
- Updated Navbar and Footer , layout also
- increased font size of Question

2023-10-09 20:58 UTC, raviikushh commented
Can You Please Check if everything is alright or not before merging

2023-10-10 16:44 UTC, eduardconstantin commented
This is a bit too much.
The blue border doesn't look too good.
If you can just replace the image for the question with just a text that would be great.

2023-10-10 16:49 UTC, raviikushh commented
> This is a bit too much.
> The blue border doesn't look too good.
> If you can just replace the image for the question with just a text that would be great.
> 
> This is how it looks on my end
> ![image](https://github.com/eduardconstantin/azure-fundamentals/assets/9199763/2c034c41-b708-4f79-b6b1-54710efd570b)
> 

Okay I'll fix it.

2023-10-11 11:04 UTC, raviikushh commented
Made few changes
- Updated UI and removed cyan color
- Adjusted Question Size so that it is clearly visible to user with good font 
- Also added some hover effect in the options and selection
- Changed the color of selection of option
- The biggest challenge was the question but I tried my best to adjust it according to user so that it looks good. It's very difficult to convert it to text because lots of files are there which are using to convert it to image and few things I'm unable to understand. We could convert it to text by using Tesseract Js bt it's too complicated here.
- I request you to review it and check whether it's looking good and accept my PR

2023-10-11 16:42 UTC, eduardconstantin requested changes

2023-10-11 16:42 UTC, eduardconstantin commented on components/Footer.tsx
> +    <footer className="flex justify-center items-baseline py-3 border-t-[1px] border-gray-300 mt-6">
we don't need a border for footer
```suggestion
    <footer className="flex justify-center items-baseline py-3">
```

2023-10-11 16:42 UTC, eduardconstantin commented on components/QuizForm.tsx
> +        <div className="flex justify-center mt-[-10px] mb-[-30px]">
don't add negative margins
```suggestion
        <div className="flex justify-center">
```

2023-10-11 16:42 UTC, eduardconstantin commented on components/TopNav.tsx
> +        <p className="font-bold text-4xl leading-7 cursor-pointer">AZURE</p>
no need to change the cursor since it's not a link
```suggestion
        <p className="font-bold text-4xl leading-7">AZURE</p>
```

2023-10-11 16:42 UTC, eduardconstantin commented on pages/api/og.tsx
> +        <div tw="flex text-center w-full h-full bg-slate-800 items-center justify-center mt-20 ">
```suggestion
        <div tw="flex text-center w-full h-full bg-slate-800 items-center justify-center ">
```

2023-10-11 16:42 UTC, eduardconstantin commented on pages/api/og.tsx
> +              width < 640 ? "text-5xl" : "text-3xl"
```suggestion
              width < 640 ? "text-3xl" : "text-2xl"
```

2023-10-11 16:42 UTC, eduardconstantin commented on pages/index.tsx
> +    <div className="mx-auto w-5/6 sm:w-2/3 lg:w-2/3 xl:w-2/4 text-center border-[1px] border-slate-500 mt-20 rounded-lg">
```suggestion
    <div className="mx-auto w-5/6 sm:w-2/3 lg:w-2/3 xl:w-2/4 text-center">
```

2023-10-11 16:42 UTC, eduardconstantin commented on pages/index.tsx
> +      <div className="flex max-sm:flex-col max-sm:align-center justify-center gap-10 m-16">
```suggestion
      <div className="flex max-sm:flex-col max-sm:align-center justify-center gap-10 sm:mx-16">
```

2023-10-11 16:42 UTC, eduardconstantin commented on pages/practice/index.tsx
> +    <div className="py-10 px-5 sm:p-10 mx-auto w-5/6 sm:w-1/2 bg-slate-800 border-2 border-slate-700 rounded-lg mt-20">
```suggestion
    <div className="py-10 px-5 sm:p-10 mx-auto w-5/6 sm:w-1/2 bg-slate-800 border-2 border-slate-700 rounded-lg">
```

2023-10-11 17:17 UTC, raviikushh commented
updated all requested changes

2023-10-11 17:19 UTC, eduardconstantin approved these changes
Great! Thank you for your contribution!

2023-10-11 17:19 UTC, merged

2023-10-11 17:20 UTC, raviikushh commented
You're most welcome., means a lot.